/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import java.awt.Dimension;

/**
 *
 * @author MAYRA PEÑA ROMAN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnProducto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnCompras = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnIngresos = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnEgresos = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnVentas = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnCajas = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnCerrar = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_mantenimiento = new javax.swing.JMenu();
        menu_Item_TipoUsuario = new javax.swing.JMenuItem();
        menu_Item_Usuario = new javax.swing.JMenuItem();
        menu_Item_Turno = new javax.swing.JMenuItem();
        menu_Item_Laboratorio = new javax.swing.JMenuItem();
        menu_Item_Categoria = new javax.swing.JMenuItem();
        menu_Item_Medida = new javax.swing.JMenuItem();
        menu_Item_Producto = new javax.swing.JMenuItem();
        menu_Item_Composicion = new javax.swing.JMenuItem();
        menu_compras = new javax.swing.JMenu();
        menu_inventario = new javax.swing.JMenu();
        menu_ventas = new javax.swing.JMenu();
        menu_caja = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPRESA X| CONECTADO COMO:ADMINISTRADOR-USUARIO: LORENA PEÑA-FARMACIA PRINCIPAL");
        setExtendedState(6);

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setForeground(new java.awt.Color(204, 255, 255));
        jToolBar1.setRollover(true);

        btnProducto.setBackground(new java.awt.Color(242, 242, 242));
        btnProducto.setForeground(new java.awt.Color(242, 242, 242));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box.png"))); // NOI18N
        btnProducto.setEnabled(false);
        btnProducto.setFocusable(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnProducto);
        jToolBar1.add(jSeparator2);

        btnCompras.setBackground(new java.awt.Color(204, 255, 255));
        btnCompras.setForeground(new java.awt.Color(204, 255, 255));
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compra.png"))); // NOI18N
        btnCompras.setEnabled(false);
        jToolBar1.add(btnCompras);
        jToolBar1.add(jSeparator1);

        btnIngresos.setBackground(new java.awt.Color(204, 255, 255));
        btnIngresos.setForeground(new java.awt.Color(204, 255, 255));
        btnIngresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ingresos.png"))); // NOI18N
        btnIngresos.setEnabled(false);
        jToolBar1.add(btnIngresos);
        jToolBar1.add(jSeparator3);

        btnEgresos.setBackground(new java.awt.Color(204, 255, 255));
        btnEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/egresos.png"))); // NOI18N
        btnEgresos.setEnabled(false);
        jToolBar1.add(btnEgresos);
        jToolBar1.add(jSeparator4);

        btnVentas.setBackground(new java.awt.Color(204, 255, 255));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cart.png"))); // NOI18N
        btnVentas.setEnabled(false);
        jToolBar1.add(btnVentas);
        jToolBar1.add(jSeparator5);

        btnCajas.setBackground(new java.awt.Color(204, 255, 255));
        btnCajas.setForeground(new java.awt.Color(204, 255, 255));
        btnCajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja_1.png"))); // NOI18N
        btnCajas.setEnabled(false);
        jToolBar1.add(btnCajas);
        jToolBar1.add(jSeparator6);

        btnCerrar.setBackground(new java.awt.Color(204, 255, 255));
        btnCerrar.setForeground(new java.awt.Color(204, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar2.png"))); // NOI18N
        jToolBar1.add(btnCerrar);

        escritorio.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        menu_mantenimiento.setText("MANTENIMIENTO");

        menu_Item_TipoUsuario.setText("Tipo de Usuario ");
        menu_Item_TipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_TipoUsuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_TipoUsuario);

        menu_Item_Usuario.setText("Usuario");
        menu_Item_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_UsuarioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Usuario);

        menu_Item_Turno.setText("Turno");
        menu_Item_Turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_TurnoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Turno);

        menu_Item_Laboratorio.setText("Laboratorio");
        menu_Item_Laboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_LaboratorioActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Laboratorio);

        menu_Item_Categoria.setText("Categoría");
        menu_Item_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_CategoriaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Categoria);

        menu_Item_Medida.setText("Medida");
        menu_Item_Medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_MedidaActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Medida);

        menu_Item_Producto.setText("Producto");
        menu_Item_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_ProductoActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Producto);

        menu_Item_Composicion.setText("Composición");
        menu_Item_Composicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_Item_ComposicionActionPerformed(evt);
            }
        });
        menu_mantenimiento.add(menu_Item_Composicion);

        jMenuBar1.add(menu_mantenimiento);

        menu_compras.setText("COMPRAS");
        menu_compras.setEnabled(false);
        jMenuBar1.add(menu_compras);

        menu_inventario.setText("INVENTARIO");
        menu_inventario.setEnabled(false);
        jMenuBar1.add(menu_inventario);

        menu_ventas.setText("VENTAS");
        menu_ventas.setEnabled(false);
        jMenuBar1.add(menu_ventas);

        menu_caja.setText("CAJA");
        menu_caja.setEnabled(false);
        jMenuBar1.add(menu_caja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addComponent(escritorio))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_Item_TipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_TipoUsuarioActionPerformed
        // TODO add your handling code here:
        TipoUsuario_IU frame = new TipoUsuario_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_Item_TipoUsuarioActionPerformed

    private void menu_Item_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_UsuarioActionPerformed
        // TODO add your handling code here:
        Usuario_IU frame = new Usuario_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_Item_UsuarioActionPerformed

    private void menu_Item_TurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_TurnoActionPerformed
        // TODO add your handling code here:
        Turno_IU frame = new Turno_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_Item_TurnoActionPerformed

    private void menu_Item_LaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_LaboratorioActionPerformed
        // TODO add your handling code here:
        Marca_IU frame = new Marca_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();

    }//GEN-LAST:event_menu_Item_LaboratorioActionPerformed

    private void menu_Item_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_CategoriaActionPerformed
        // TODO add your handling code here:
        Categoria_IU frame = new Categoria_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_Item_CategoriaActionPerformed

    private void menu_Item_MedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_MedidaActionPerformed
        // TODO add your handling code here:
        Medida_IU frame = new Medida_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_Item_MedidaActionPerformed

    private void menu_Item_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_ProductoActionPerformed
        // TODO add your handling code here:
        Producto_IU frame = new Producto_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_Item_ProductoActionPerformed

    private void menu_Item_ComposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_Item_ComposicionActionPerformed
        // TODO add your handling code here:
        Composicion_IU frame = new Composicion_IU();
        escritorio.add(frame);
        Dimension desktopSize = escritorio.getSize();
        Dimension FrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height) / 2);

        frame.show();
    }//GEN-LAST:event_menu_Item_ComposicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCajas;
    public javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnCompras;
    private javax.swing.JLabel btnEgresos;
    private javax.swing.JLabel btnIngresos;
    private javax.swing.JButton btnProducto;
    private javax.swing.JLabel btnVentas;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menu_Item_Categoria;
    private javax.swing.JMenuItem menu_Item_Composicion;
    private javax.swing.JMenuItem menu_Item_Laboratorio;
    private javax.swing.JMenuItem menu_Item_Medida;
    private javax.swing.JMenuItem menu_Item_Producto;
    private javax.swing.JMenuItem menu_Item_TipoUsuario;
    private javax.swing.JMenuItem menu_Item_Turno;
    private javax.swing.JMenuItem menu_Item_Usuario;
    public javax.swing.JMenu menu_caja;
    private javax.swing.JMenu menu_compras;
    private javax.swing.JMenu menu_inventario;
    private javax.swing.JMenu menu_mantenimiento;
    private javax.swing.JMenu menu_ventas;
    // End of variables declaration//GEN-END:variables
}
